### PR TITLE
Begin the great SQLX migration

### PR DESCRIPTION
**Pull request by triphora**
Draft.

### CODE REVIEW

**Comment by kylerchin** [comment]
Incredible work so far! Thank you so much!

**Comment by kylerchin** [comment]
Is `.sqlx` supposed to be in the .gitignore? I'm not entirely familiar with this but I will move everything from now on to sqlx!

**Comment by triphora** [comment]
No, sqlx is supposed to be checked into version control.

**Comment by kylerchin** [comment]
Hello! I've stolen some of your ideas and brought them over to https://github.com/catenarytransit/catenary-backend/pull/3

**Comment by kylerchin** [comment]
Feel free to ask me if you have any further questions or want clarification on anything! I'm open to more suggestions

**Comment by kylerchin** [comment]
Closing this, changes have been copied into #3

**Pull request closed without merging**
